# Generated by Django 3.2 on 2021-04-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatchers', '0002_car'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'диспетчер', 'verbose_name_plural': 'диспетчера'},
        ),
    ]
