# Generated by Django 3.2 on 2021-04-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desired_time',
            field=models.TimeField(verbose_name='желаемое время подачи авто'),
        ),
    ]
